name = "lordfilm-proxy-iwalker2005"
main = "worker.js"
compatibility_date = "2026-02-26"
workers_dev = true

[vars]
ALLOWED_HOSTS = "lordfilm-2026.org,www.lordfilm-2026.org,lordfilmpuq.study,www.lordfilmpuq.study,gentalmen-lordfilm.ru,www.gentalmen-lordfilm.ru,12-angry-men-lordfilm.ru,www.12-angry-men-lordfilm.ru,spongebob-squarepants-lordfilms.ru,www.spongebob-squarepants-lordfilms.ru,html.duckduckgo.com,*.lordfilm.ru,plapi.cdnvideohub.com,player.cdnvideohub.com,api.namy.ws,api.kinogram.best,api.apbugall.org,kodikapi.com,kodik.info,kodik.biz,rezka.ag,hdrezka.ag,filmix.my,kinobase.org,api.rstprgapipt.com,*.okcdn.ru,*.allarknow.online,*.stloadi.live"
VIDEO_ALLOWED_HOSTS = "*.okcdn.ru,*.vkuser.net,*.interkh.com,*.stloadi.live,*.kodik.info,*.kodik.biz,*.kodikapi.com,*.kinobase.org,*.filmix.my,*.rezka.ag,*.rezka.pub,plapi.cdnvideohub.com,player.cdnvideohub.com"
UPSTREAM_TIMEOUT_MS = "12000"
